version: '3.8'
services:

  postgres:
    image: postgres:13.5
    container_name: productos_database
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - '5434:5432'

    volumes:
      - ./postgres:/var/lib/postgresql/data
